### ISSUE TITLE
Bug: Typing in filter/search queries results in double-keying characters (Windows 11)

### ISSUE THREAD

**Issue by jqnatividad** [YS-L/csvlens#30]
So you can't effectively filter/search as characters are entered twice per one keystroke.

**Comment by YS-L** [comment]
Thanks for reporting! I could reproduce this in a VM.

This is caused by an issue in crossterm 0.26: https://github.com/crossterm-rs/crossterm/pull/778

While the upstream fix is still in progress, one way that seems to work is to revert crossterm back to 0.25 for windows. I pushed the change in the main branch (2ef45b37b1bec4bf23420860a6cb36904609518b). Let me know if that resolves the issue for you.

**Comment by jqnatividad** [comment]
Hi @YS-L . I can confirm that this now works on Windows.  Thanks!
